version: '3.8'

services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: your-django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=weather
      - POSTGRES_USER=oleksii
      - POSTGRES_PASSWORD=bgy845ikfs
    ports:
      - "15432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Weather.celery worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A Weather.celery beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: